version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/Sofia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /opt/mosquitto/config:/mosquitto/config/
    ports:
      - 1883:1883

  tailscale:
    hostname: myservice                         # This will become the tailscale device name
    image: tailscale/tailscale
    volumes:
      - "/var/lib:/var/lib"        # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
